name: Main CI
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.19"
          check-latest: true
          cache: true

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: --verbose

  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - macOS
        go:
          - 19

    name: "${{ matrix.platform }} | 1.${{ matrix.go }}.x"
    runs-on: ${{ matrix.platform }}-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.${{ matrix.go }}.x
          cache: true

      - name: ⚡ Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - run: |
          export GOBIN=$HOME/go/bin
          go install github.com/kyoh86/richgo@latest
          go install github.com/mitchellh/gox@latest

      - run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH make richtest
